export default {
    "gender": ["Male", "Female"],
    "wantTravel": ["Yes", "No"],
    "salary": ["Less Than $25,000", "$25,000", "$35,000", "$50,000", "$75,000", "$100,000 to $150,000", "$150,001 +"],
    "ethnicity": ["White/Caucasian", "Black/African", "Latino/Hispanic", "Native American", "Middle Eastern", "Pacific Islander", "East Indian", "Other"],
    "pets": ["Yes", "No, but not sure if want some", "No, but I want some"],
    "height": ["5'0\"", "5'1\"", "5'2\"", "5'3\"", "5'4\"", "5'5\"", "5'6\"", "5'7\"", "5'8\"", "5'9\"", "5'10\"", "5'11\"", "6'0\"", "6'1\"", "6'2\"", "6'3\"", "6'4\"", "6'5\"", "6'6\"", "and up"],
    "hasChildren": ["No", "Yes - live away from home", "Yes - sometimes live at home", "Yes - live at home"],
    "wantChildren": ["No", "Definitely", "Someday"],
    "educationLevel": ["High School", "Some College", "Associates degree", "Bachelor's degree", "Graduate degree", "PhD/Post Doctoral"],
    "religion": ["Christian", "Catholic", "Jewish", "Islam", "Buddhist", "Hindu", "Jain", "Agnostic", "Athiest", "Other"],
    "drinkingHabits": ["Frequently", "Socially", "Rarely", "Never", "Never, but I tolerate drinking", "Never, I can't stand drinking"],
    "smokingHabits": ["Frequently", "Socially", "Rarely", "Never, but I tolerate smoking", "Never, I can't stand smoking"],
    "bodyType": ["Skinny", "Athletic", "Average", "Chubby", "Curvy"],
    "eatingHabits": ["Eat Anything", "Healthy", "Paleo", "Vegetarian", "Vegan", "Macrobiotic", "Kosher", "Halal", "Other"],
    "seeking": ["Friends", "Casual Encounters", "Relationship", "Marriage"],
    "range": ["5", "10", "20", "40", "70", "100", "200"],
    "relocate": ["Yes", "No", "Undecided"],
    "age": [18,19,20,21,22,23]
}
